# Configuration de la base de données
spring.datasource.url=jdbc:mysql://localhost:3306/etudedecas
spring.datasource.username=root
spring.datasource.password=123456

# Activer les logs des requêtes SQL
spring.jpa.show-sql=true

# Auto-configuration des tables (adapter selon votre besoin)
spring.jpa.hibernate.ddl-auto=update

# Formatage lisible des logs SQL (facultatif)
spring.jpa.properties.hibernate.format_sql=true

# Configuration de la console H2 (si utilisée pour les tests)
spring.h2.console.enabled=true

# Paramètres gRPC
grpc.server.port=9090
logging.level.io.grpc=DEBUG
logging.level.net.devh.grpc.server=DEBUG

